import './global.css';

export const metadata = {
  title: {
    template: '%s | Grey Healer Vault',
    default: 'Grey Healer Vault',
  },
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='overflow-hidden'>{children}</body>
    </html>
  );
}
